### PR TITLE
adding PlatformIO build support

### PR DESCRIPTION
**Pull request by universam1**
PlatformIO built simplifies the usage quite a bit!

Built and flashed my person DSO-150 this way, works perfectly fine

`pio run -t upload`

### CODE REVIEW

**Comment by universam1** [comment]
@michar71 any objections? This PR should be cost-free to add

**Comment by positron96** [comment]
That's an awesome pull request! I did not have to install some vendor-specific IDE just to compile the project! I cloned the branch, opened in VSCode and hit the build button, and it does the rest.

I have yet to flash my DSO although

**Comment by universam1** [comment]
> Does the binary work with original (I hope) DSO150?

Yes it works fine on my original DSO150 :+1: 

BTW I also flashed directly via `PIO` by this command `pio run -t upload`

**Comment by positron96** [comment]
Well, I flashed with PIO successfully, but the firmware does not work for me. Gives white screen, seems to go to HardFault from printf inside zconfig.cpp#printConfig. Could you please advise anything? I'm using stlink v2 clone

**Comment by positron96** [comment]
Ah, nevermind, I found this article that fixed the problem https://github.com/michar71/Open-DSO-150/issues/19

**Comment by michar71** [comment]
Hmmm... How do you open the project in Visual Studio Code with Platform IO?
Finally wanted to give it a try and ran into all kinds of directory/linker problems.....

When I create a new Project it works but  opening an existing project from STM32IDE seem to cause all kinds of pain...

**Comment by positron96** [comment]
I just opened folder with platformio.ini inside VS Code and it did the rest. First compilation took some time because it was downloading toolchain, tools, debugging stuff, library for stm32cube etc. But it really was one click to open the folder, one click to build and voila, I got hex file!

**Pull request merged**
